# Change these first
owner: DSITD-Universitas-Hasanuddin # Your GitHub organization or username, where this repository lives
repo: uptime-checker # The name of this repository

sites:
  - name: Unhas Main
    url: https://unhas.ac.id
  - name: Apps
    url: https://apps.unhas.ac.id
  - name: Neosia
    url: https://neosia.unhas.ac.id
  - name: SSO Unhas
    url: https://sso.unhas.ac.id
  - name: Dikmawa
    url: https://dikmawa.unhas.ac.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-checker
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime Unhas Website"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
