# Change these first
owner: DSITD-Universitas-Hasanuddin # Your GitHub organization or username, where this repository lives
repo: uptime-checker # The name of this repository

sites:
  - name: Unhas Main
    url: https://unhas.ac.id
  - name: Apps
    url: https://apps.unhas.ac.id
  - name: Neosia
    url: https://neosia.unhas.ac.id
  - name: SSO Unhas
    url: https://sso.unhas.ac.id
  - name: Dikmawa
    url: https://dikmawa.unhas.ac.id
  - name: Sister Unhas
    url: http://sister.unhas.ac.id
  - name: Fakultas Teknik
    url: http://eng.unhas.ac.id/fakultas
  - name: Fakultas Kedokteran
    url: http://med.unhas.ac.id
  - name: Fakultas Ekonomi
    url: http://feb.unhas.ac.id
  - name: Fakultas IKP
    url: http://fikp.unhas.ac.id
  - name: Fakultas KM
    url: http://fkm.unhas.ac.id
  - name: Fakultas Farmasi
    url: http://farmasi.unhas.ac.id
  - name: Fakultas Ilmu Budaya
    url: http://ilmubudaya.unhas.ac.id
  - name: Fakultas ISIP
    url: http://fisip.unhas.ac.id/newfisip
  - name: Fakultas Pertanian
    url: http://agriculture.unhas.ac.id
  - name: Fakultas Peternakan
    url: http://peternakan.unhas.ac.id
  - name: Fakultas Kehutanan
    url: http://forestry.unhas.ac.id
  - name: Fakultas Hukum
    url: http://lawfaculty.unhas.ac.id
  - name: Fakultas Kedokteran Gigi
    url: http://dent.unhas.ac.id
  - name: Fakultas Vokasi
    url: http://vokasi.unhas.ac.id
  - name: Fakultas Keperawatan
    url: http://nursing.unhas.ac.id
  - name: Fakultas MIPA
    url: http://sci.unhas.ac.id
  - name: LP2M
    url: http://lp2m.unhas.ac.id
  



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-checker
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime Unhas Website"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
